on:
  push:
    tags:
      - '*'

name: Create Jeffrey CLI Artifact

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: petrbouda/jeffrey-builder

    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Maven
      env:
        JEFFREY_TAG_VERSION: ${{ github.ref_name }}
      run: mvn clean package

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset - Application
      id: upload-release-asset-application
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/build-app/target/jeffrey-cli.jar
        asset_name: jeffrey-cli.jar
        asset_content_type: application/java-archive
